name: flutter_ui_kit
description: "A comprehensive Flutter UI kit with theming, components, and design presets."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  flutter_svg: ^2.0.17
  flutter_styled_toast: ^2.2.1
  flutter_animated_dialog_updated: ^1.0.1
  intl_phone_field: ^3.2.0
  loading_overlay: ^0.3.0
  intl: ^0.19.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
